* *Q1:*

In [3]:
import pandas as pd
pd.__version__

'3.0.6'

* *Q2:*

In [59]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.describe().round()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.0,10000.0,10000.0,10000.0,9123.0,10000.0,9736.0,10000.0
mean,2000.0,4.0,2269.0,6.0,254.0,4287.0,19.0,30.0
std,14.0,1.0,183.0,1.0,23.0,266.0,1.0,3.0
min,1975.0,2.0,1590.0,4.0,171.0,3320.0,14.0,20.0
25%,1987.0,3.0,2150.0,6.0,239.0,4110.0,18.0,28.0
50%,2000.0,4.0,2270.0,6.0,254.0,4280.0,19.0,30.0
75%,2012.0,4.0,2390.0,6.0,270.0,4470.0,20.0,32.0
max,2024.0,5.0,3110.0,8.0,334.0,5460.0,24.0,41.0

* *Q3:*

In [ ]:
df.fuel_type.nunique()

3

* *Q4:*

In [ ]:
df.isnull().sum()
# 2 columns / horsepower 877 missing values / acceleration 264 missing values

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

* *Q5:*

In [ ]:
df[df['origin'] == 'Asia'].describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,2994.00,2994.00,2994.00,2994.00,2729.00,2994.00,2994.00,2994.00
mean,1999.44,3.50,2252.45,6.00,247.66,4235.00,18.90,30.74
std,14.25,0.95,184.01,0.55,21.32,263.52,1.32,2.84
min,1975.00,2.00,1590.00,4.00,174.00,3320.00,14.40,21.30
25%,1987.00,3.00,2130.00,6.00,234.00,4060.00,18.00,28.70
50%,1999.00,4.00,2260.00,6.00,248.00,4230.00,18.90,30.70
75%,2012.00,4.00,2370.00,6.00,262.00,4410.00,19.80,32.50
max,2024.00,5.00,3020.00,8.00,334.00,5280.00,23.80,41.20

* *Q6:*

In [ ]:
df['horsepower'].describe() # 50%(median) = 254.0
most_frequent=df.horsepower.value_counts().index[0] #252.0 most frequent
df['horsepower']=df.horsepower.fillna(most_frequent)
df.horsepower.describe() # now it 252.0

count    10000.000000
mean       254.231500
std         21.830757
min        171.000000
25%        241.000000
50%        252.000000
75%        268.000000
max        334.000000
Name: horsepower, dtype: float64

* *Q7:*

In [119]:
import numpy as np
asia=df[df['origin']=='Asia']
all_asia=asia[['vehicle_weight', 'model_year']]
all_asia_7=all_asia.head(7)
x=all_asia_7.values
x_transpose=x.T
xtx=x_transpose.dot(x)
xtx
xtx_inv=np.linalg.inv(xtx)
y=np.array([1100,1300,800,900,1000,1100,1200])
w=xtx_inv.dot(x_transpose).dot(y)
w.sum()

np.float64(0.36919696904925486)